onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /system_tb/CLK
add wave -noupdate /system_tb/nRST
add wave -noupdate /system_tb/DUT/CPU/DP/CLK
add wave -noupdate /system_tb/DUT/CPU/DP/nRST
add wave -noupdate /system_tb/DUT/CPU/DP/jump_addr
add wave -noupdate /system_tb/DUT/CPU/DP/branch_addr
add wave -noupdate /system_tb/DUT/CPU/DP/imm16
add wave -noupdate /system_tb/DUT/CPU/DP/shamt
add wave -noupdate /system_tb/DUT/CPU/DP/imm16_SignExtend
add wave -noupdate /system_tb/DUT/CPU/DP/pc_input
add wave -noupdate /system_tb/DUT/CPU/DP/pc_output
add wave -noupdate /system_tb/DUT/CPU/DP/pc_nextstate
add wave -noupdate /system_tb/DUT/CPU/DP/pc_wen
add wave -noupdate /system_tb/DUT/CPU/CC/CLK
add wave -noupdate /system_tb/DUT/CPU/CC/nRST
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/PCSrc
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/RegWr
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/ExtOp
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/iREN
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/dREN
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/dWEN
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/jump
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/jal
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/mem2reg
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/halt
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/lui
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/jr
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/zero
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/overflow
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/ihit
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/dhit
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/ALUSrc
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/RegDst
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/ALUop
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/Instruct
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/funct
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/halt
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/ihit
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/imemREN
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/imemload
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/imemaddr
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dhit
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/datomic
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemREN
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemWEN
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/flushed
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemload
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemstore
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemaddr
add wave -noupdate /system_tb/DUT/CPU/DP/ruif/ihit
add wave -noupdate /system_tb/DUT/CPU/DP/ruif/dhit
add wave -noupdate /system_tb/DUT/CPU/DP/ruif/dmemwen
add wave -noupdate /system_tb/DUT/CPU/DP/ruif/dmemren
add wave -noupdate /system_tb/DUT/CPU/DP/ruif/imemren
add wave -noupdate /system_tb/DUT/CPU/DP/ruif/iREN
add wave -noupdate /system_tb/DUT/CPU/DP/ruif/dWEN
add wave -noupdate /system_tb/DUT/CPU/DP/ruif/dREN
add wave -noupdate /system_tb/DUT/CPU/DP/ruif/halt
add wave -noupdate /system_tb/DUT/CPU/DP/aluif/ALUOP
add wave -noupdate /system_tb/DUT/CPU/DP/aluif/port_A
add wave -noupdate /system_tb/DUT/CPU/DP/aluif/port_B
add wave -noupdate /system_tb/DUT/CPU/DP/aluif/output_port
add wave -noupdate /system_tb/DUT/CPU/DP/aluif/negative
add wave -noupdate /system_tb/DUT/CPU/DP/aluif/overflow
add wave -noupdate /system_tb/DUT/CPU/DP/aluif/zero
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/WEN
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/wsel
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/rsel1
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/rsel2
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/wdat
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/rdat1
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/rdat2
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {1309790 ns} {1310790 ns}
